// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-tracker/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGraphService creates a new instance of MockGraphService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphService {
	mock := &MockGraphService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGraphService is an autogenerated mock type for the GraphService type
type MockGraphService struct {
	mock.Mock
}

type MockGraphService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphService) EXPECT() *MockGraphService_Expecter {
	return &MockGraphService_Expecter{mock: &_m.Mock}
}

// AddEdge provides a mock function for the type MockGraphService
func (_mock *MockGraphService) AddEdge(ctx context.Context, trackingSet string, edge types.Edge) (types.Edge, error) {
	ret := _mock.Called(ctx, trackingSet, edge)

	if len(ret) == 0 {
		panic("no return value specified for AddEdge")
	}

	var r0 types.Edge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Edge) (types.Edge, error)); ok {
		return returnFunc(ctx, trackingSet, edge)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Edge) types.Edge); ok {
		r0 = returnFunc(ctx, trackingSet, edge)
	} else {
		r0 = ret.Get(0).(types.Edge)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Edge) error); ok {
		r1 = returnFunc(ctx, trackingSet, edge)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphService_AddEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEdge'
type MockGraphService_AddEdge_Call struct {
	*mock.Call
}

// AddEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - edge types.Edge
func (_e *MockGraphService_Expecter) AddEdge(ctx interface{}, trackingSet interface{}, edge interface{}) *MockGraphService_AddEdge_Call {
	return &MockGraphService_AddEdge_Call{Call: _e.mock.On("AddEdge", ctx, trackingSet, edge)}
}

func (_c *MockGraphService_AddEdge_Call) Run(run func(ctx context.Context, trackingSet string, edge types.Edge)) *MockGraphService_AddEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Edge
		if args[2] != nil {
			arg2 = args[2].(types.Edge)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphService_AddEdge_Call) Return(edge1 types.Edge, err error) *MockGraphService_AddEdge_Call {
	_c.Call.Return(edge1, err)
	return _c
}

func (_c *MockGraphService_AddEdge_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, edge types.Edge) (types.Edge, error)) *MockGraphService_AddEdge_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocking provides a mock function for the type MockGraphService
func (_mock *MockGraphService) GetBlocking(ctx context.Context, trackingSet string, ticketID string) ([]types.Ticket, error) {
	ret := _mock.Called(ctx, trackingSet, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocking")
	}

	var r0 []types.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]types.Ticket, error)); ok {
		return returnFunc(ctx, trackingSet, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []types.Ticket); ok {
		r0 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphService_GetBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocking'
type MockGraphService_GetBlocking_Call struct {
	*mock.Call
}

// GetBlocking is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticketID string
func (_e *MockGraphService_Expecter) GetBlocking(ctx interface{}, trackingSet interface{}, ticketID interface{}) *MockGraphService_GetBlocking_Call {
	return &MockGraphService_GetBlocking_Call{Call: _e.mock.On("GetBlocking", ctx, trackingSet, ticketID)}
}

func (_c *MockGraphService_GetBlocking_Call) Run(run func(ctx context.Context, trackingSet string, ticketID string)) *MockGraphService_GetBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphService_GetBlocking_Call) Return(tickets []types.Ticket, err error) *MockGraphService_GetBlocking_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockGraphService_GetBlocking_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticketID string) ([]types.Ticket, error)) *MockGraphService_GetBlocking_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function for the type MockGraphService
func (_mock *MockGraphService) GetChildren(ctx context.Context, trackingSet string, parentID string) ([]types.Ticket, error) {
	ret := _mock.Called(ctx, trackingSet, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []types.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]types.Ticket, error)); ok {
		return returnFunc(ctx, trackingSet, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []types.Ticket); ok {
		r0 = returnFunc(ctx, trackingSet, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphService_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockGraphService_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - parentID string
func (_e *MockGraphService_Expecter) GetChildren(ctx interface{}, trackingSet interface{}, parentID interface{}) *MockGraphService_GetChildren_Call {
	return &MockGraphService_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx, trackingSet, parentID)}
}

func (_c *MockGraphService_GetChildren_Call) Run(run func(ctx context.Context, trackingSet string, parentID string)) *MockGraphService_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphService_GetChildren_Call) Return(tickets []types.Ticket, err error) *MockGraphService_GetChildren_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockGraphService_GetChildren_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, parentID string) ([]types.Ticket, error)) *MockGraphService_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetGraph provides a mock function for the type MockGraphService
func (_mock *MockGraphService) GetGraph(ctx context.Context, trackingSet string) (types.Graph, error) {
	ret := _mock.Called(ctx, trackingSet)

	if len(ret) == 0 {
		panic("no return value specified for GetGraph")
	}

	var r0 types.Graph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.Graph, error)); ok {
		return returnFunc(ctx, trackingSet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.Graph); ok {
		r0 = returnFunc(ctx, trackingSet)
	} else {
		r0 = ret.Get(0).(types.Graph)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, trackingSet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphService_GetGraph_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGraph'
type MockGraphService_GetGraph_Call struct {
	*mock.Call
}

// GetGraph is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
func (_e *MockGraphService_Expecter) GetGraph(ctx interface{}, trackingSet interface{}) *MockGraphService_GetGraph_Call {
	return &MockGraphService_GetGraph_Call{Call: _e.mock.On("GetGraph", ctx, trackingSet)}
}

func (_c *MockGraphService_GetGraph_Call) Run(run func(ctx context.Context, trackingSet string)) *MockGraphService_GetGraph_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGraphService_GetGraph_Call) Return(graph types.Graph, err error) *MockGraphService_GetGraph_Call {
	_c.Call.Return(graph, err)
	return _c
}

func (_c *MockGraphService_GetGraph_Call) RunAndReturn(run func(ctx context.Context, trackingSet string) (types.Graph, error)) *MockGraphService_GetGraph_Call {
	_c.Call.Return(run)
	return _c
}

// ListEdges provides a mock function for the type MockGraphService
func (_mock *MockGraphService) ListEdges(ctx context.Context, trackingSet string, ticketID string) ([]types.Edge, error) {
	ret := _mock.Called(ctx, trackingSet, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for ListEdges")
	}

	var r0 []types.Edge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]types.Edge, error)); ok {
		return returnFunc(ctx, trackingSet, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []types.Edge); ok {
		r0 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Edge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphService_ListEdges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListEdges'
type MockGraphService_ListEdges_Call struct {
	*mock.Call
}

// ListEdges is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticketID string
func (_e *MockGraphService_Expecter) ListEdges(ctx interface{}, trackingSet interface{}, ticketID interface{}) *MockGraphService_ListEdges_Call {
	return &MockGraphService_ListEdges_Call{Call: _e.mock.On("ListEdges", ctx, trackingSet, ticketID)}
}

func (_c *MockGraphService_ListEdges_Call) Run(run func(ctx context.Context, trackingSet string, ticketID string)) *MockGraphService_ListEdges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphService_ListEdges_Call) Return(edges []types.Edge, err error) *MockGraphService_ListEdges_Call {
	_c.Call.Return(edges, err)
	return _c
}

func (_c *MockGraphService_ListEdges_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticketID string) ([]types.Edge, error)) *MockGraphService_ListEdges_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEdge provides a mock function for the type MockGraphService
func (_mock *MockGraphService) RemoveEdge(ctx context.Context, trackingSet string, edge types.Edge) error {
	ret := _mock.Called(ctx, trackingSet, edge)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEdge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Edge) error); ok {
		r0 = returnFunc(ctx, trackingSet, edge)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGraphService_RemoveEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEdge'
type MockGraphService_RemoveEdge_Call struct {
	*mock.Call
}

// RemoveEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - edge types.Edge
func (_e *MockGraphService_Expecter) RemoveEdge(ctx interface{}, trackingSet interface{}, edge interface{}) *MockGraphService_RemoveEdge_Call {
	return &MockGraphService_RemoveEdge_Call{Call: _e.mock.On("RemoveEdge", ctx, trackingSet, edge)}
}

func (_c *MockGraphService_RemoveEdge_Call) Run(run func(ctx context.Context, trackingSet string, edge types.Edge)) *MockGraphService_RemoveEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Edge
		if args[2] != nil {
			arg2 = args[2].(types.Edge)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphService_RemoveEdge_Call) Return(err error) *MockGraphService_RemoveEdge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGraphService_RemoveEdge_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, edge types.Edge) error) *MockGraphService_RemoveEdge_Call {
	_c.Call.Return(run)
	return _c
}
