// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-tracker/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlanService creates a new instance of MockPlanService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanService {
	mock := &MockPlanService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlanService is an autogenerated mock type for the PlanService type
type MockPlanService struct {
	mock.Mock
}

type MockPlanService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanService) EXPECT() *MockPlanService_Expecter {
	return &MockPlanService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPlanService
func (_mock *MockPlanService) Create(ctx context.Context, trackingSet string, plan types.Plan) (types.Plan, error) {
	ret := _mock.Called(ctx, trackingSet, plan)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 types.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Plan) (types.Plan, error)); ok {
		return returnFunc(ctx, trackingSet, plan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Plan) types.Plan); ok {
		r0 = returnFunc(ctx, trackingSet, plan)
	} else {
		r0 = ret.Get(0).(types.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Plan) error); ok {
		r1 = returnFunc(ctx, trackingSet, plan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPlanService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - plan types.Plan
func (_e *MockPlanService_Expecter) Create(ctx interface{}, trackingSet interface{}, plan interface{}) *MockPlanService_Create_Call {
	return &MockPlanService_Create_Call{Call: _e.mock.On("Create", ctx, trackingSet, plan)}
}

func (_c *MockPlanService_Create_Call) Run(run func(ctx context.Context, trackingSet string, plan types.Plan)) *MockPlanService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Plan
		if args[2] != nil {
			arg2 = args[2].(types.Plan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanService_Create_Call) Return(plan1 types.Plan, err error) *MockPlanService_Create_Call {
	_c.Call.Return(plan1, err)
	return _c
}

func (_c *MockPlanService_Create_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, plan types.Plan) (types.Plan, error)) *MockPlanService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPlanService
func (_mock *MockPlanService) Delete(ctx context.Context, trackingSet string, id string) error {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlanService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPlanService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockPlanService_Expecter) Delete(ctx interface{}, trackingSet interface{}, id interface{}) *MockPlanService_Delete_Call {
	return &MockPlanService_Delete_Call{Call: _e.mock.On("Delete", ctx, trackingSet, id)}
}

func (_c *MockPlanService_Delete_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockPlanService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanService_Delete_Call) Return(err error) *MockPlanService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlanService_Delete_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) error) *MockPlanService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPlanService
func (_mock *MockPlanService) Get(ctx context.Context, trackingSet string, id string) (types.Plan, error) {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (types.Plan, error)); ok {
		return returnFunc(ctx, trackingSet, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) types.Plan); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Get(0).(types.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPlanService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockPlanService_Expecter) Get(ctx interface{}, trackingSet interface{}, id interface{}) *MockPlanService_Get_Call {
	return &MockPlanService_Get_Call{Call: _e.mock.On("Get", ctx, trackingSet, id)}
}

func (_c *MockPlanService_Get_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockPlanService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanService_Get_Call) Return(plan types.Plan, err error) *MockPlanService_Get_Call {
	_c.Call.Return(plan, err)
	return _c
}

func (_c *MockPlanService_Get_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) (types.Plan, error)) *MockPlanService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPlanService
func (_mock *MockPlanService) List(ctx context.Context, trackingSet string) ([]types.Plan, error) {
	ret := _mock.Called(ctx, trackingSet)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []types.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]types.Plan, error)); ok {
		return returnFunc(ctx, trackingSet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []types.Plan); ok {
		r0 = returnFunc(ctx, trackingSet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Plan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, trackingSet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPlanService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
func (_e *MockPlanService_Expecter) List(ctx interface{}, trackingSet interface{}) *MockPlanService_List_Call {
	return &MockPlanService_List_Call{Call: _e.mock.On("List", ctx, trackingSet)}
}

func (_c *MockPlanService_List_Call) Run(run func(ctx context.Context, trackingSet string)) *MockPlanService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlanService_List_Call) Return(plans []types.Plan, err error) *MockPlanService_List_Call {
	_c.Call.Return(plans, err)
	return _c
}

func (_c *MockPlanService_List_Call) RunAndReturn(run func(ctx context.Context, trackingSet string) ([]types.Plan, error)) *MockPlanService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPlanService
func (_mock *MockPlanService) Update(ctx context.Context, trackingSet string, plan types.Plan) (types.Plan, error) {
	ret := _mock.Called(ctx, trackingSet, plan)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 types.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Plan) (types.Plan, error)); ok {
		return returnFunc(ctx, trackingSet, plan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Plan) types.Plan); ok {
		r0 = returnFunc(ctx, trackingSet, plan)
	} else {
		r0 = ret.Get(0).(types.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, types.Plan) error); ok {
		r1 = returnFunc(ctx, trackingSet, plan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPlanService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - plan types.Plan
func (_e *MockPlanService_Expecter) Update(ctx interface{}, trackingSet interface{}, plan interface{}) *MockPlanService_Update_Call {
	return &MockPlanService_Update_Call{Call: _e.mock.On("Update", ctx, trackingSet, plan)}
}

func (_c *MockPlanService_Update_Call) Run(run func(ctx context.Context, trackingSet string, plan types.Plan)) *MockPlanService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Plan
		if args[2] != nil {
			arg2 = args[2].(types.Plan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanService_Update_Call) Return(plan1 types.Plan, err error) *MockPlanService_Update_Call {
	_c.Call.Return(plan1, err)
	return _c
}

func (_c *MockPlanService_Update_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, plan types.Plan) (types.Plan, error)) *MockPlanService_Update_Call {
	_c.Call.Return(run)
	return _c
}
