// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockcontroller

import (
	"context"

	"github.com/alexandremahdhaoui/forge-tracker/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrackingSetService creates a new instance of MockTrackingSetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrackingSetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrackingSetService {
	mock := &MockTrackingSetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrackingSetService is an autogenerated mock type for the TrackingSetService type
type MockTrackingSetService struct {
	mock.Mock
}

type MockTrackingSetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrackingSetService) EXPECT() *MockTrackingSetService_Expecter {
	return &MockTrackingSetService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTrackingSetService
func (_mock *MockTrackingSetService) Create(ctx context.Context, ts types.TrackingSet) (types.TrackingSet, error) {
	ret := _mock.Called(ctx, ts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 types.TrackingSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.TrackingSet) (types.TrackingSet, error)); ok {
		return returnFunc(ctx, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.TrackingSet) types.TrackingSet); ok {
		r0 = returnFunc(ctx, ts)
	} else {
		r0 = ret.Get(0).(types.TrackingSet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.TrackingSet) error); ok {
		r1 = returnFunc(ctx, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackingSetService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTrackingSetService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ts types.TrackingSet
func (_e *MockTrackingSetService_Expecter) Create(ctx interface{}, ts interface{}) *MockTrackingSetService_Create_Call {
	return &MockTrackingSetService_Create_Call{Call: _e.mock.On("Create", ctx, ts)}
}

func (_c *MockTrackingSetService_Create_Call) Run(run func(ctx context.Context, ts types.TrackingSet)) *MockTrackingSetService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.TrackingSet
		if args[1] != nil {
			arg1 = args[1].(types.TrackingSet)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackingSetService_Create_Call) Return(trackingSet types.TrackingSet, err error) *MockTrackingSetService_Create_Call {
	_c.Call.Return(trackingSet, err)
	return _c
}

func (_c *MockTrackingSetService_Create_Call) RunAndReturn(run func(ctx context.Context, ts types.TrackingSet) (types.TrackingSet, error)) *MockTrackingSetService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTrackingSetService
func (_mock *MockTrackingSetService) Delete(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrackingSetService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTrackingSetService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTrackingSetService_Expecter) Delete(ctx interface{}, name interface{}) *MockTrackingSetService_Delete_Call {
	return &MockTrackingSetService_Delete_Call{Call: _e.mock.On("Delete", ctx, name)}
}

func (_c *MockTrackingSetService_Delete_Call) Run(run func(ctx context.Context, name string)) *MockTrackingSetService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackingSetService_Delete_Call) Return(err error) *MockTrackingSetService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrackingSetService_Delete_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockTrackingSetService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTrackingSetService
func (_mock *MockTrackingSetService) Get(ctx context.Context, name string) (types.TrackingSet, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.TrackingSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.TrackingSet, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.TrackingSet); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(types.TrackingSet)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackingSetService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTrackingSetService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTrackingSetService_Expecter) Get(ctx interface{}, name interface{}) *MockTrackingSetService_Get_Call {
	return &MockTrackingSetService_Get_Call{Call: _e.mock.On("Get", ctx, name)}
}

func (_c *MockTrackingSetService_Get_Call) Run(run func(ctx context.Context, name string)) *MockTrackingSetService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrackingSetService_Get_Call) Return(trackingSet types.TrackingSet, err error) *MockTrackingSetService_Get_Call {
	_c.Call.Return(trackingSet, err)
	return _c
}

func (_c *MockTrackingSetService_Get_Call) RunAndReturn(run func(ctx context.Context, name string) (types.TrackingSet, error)) *MockTrackingSetService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTrackingSetService
func (_mock *MockTrackingSetService) List(ctx context.Context) ([]types.TrackingSet, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []types.TrackingSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]types.TrackingSet, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []types.TrackingSet); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.TrackingSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrackingSetService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTrackingSetService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTrackingSetService_Expecter) List(ctx interface{}) *MockTrackingSetService_List_Call {
	return &MockTrackingSetService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTrackingSetService_List_Call) Run(run func(ctx context.Context)) *MockTrackingSetService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTrackingSetService_List_Call) Return(trackingSets []types.TrackingSet, err error) *MockTrackingSetService_List_Call {
	_c.Call.Return(trackingSets, err)
	return _c
}

func (_c *MockTrackingSetService_List_Call) RunAndReturn(run func(ctx context.Context) ([]types.TrackingSet, error)) *MockTrackingSetService_List_Call {
	_c.Call.Return(run)
	return _c
}
