// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-tracker/internal/adapter"
	"github.com/alexandremahdhaoui/forge-tracker/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTicketStore creates a new instance of MockTicketStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketStore {
	mock := &MockTicketStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTicketStore is an autogenerated mock type for the TicketStore type
type MockTicketStore struct {
	mock.Mock
}

type MockTicketStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketStore) EXPECT() *MockTicketStore_Expecter {
	return &MockTicketStore_Expecter{mock: &_m.Mock}
}

// AddComment provides a mock function for the type MockTicketStore
func (_mock *MockTicketStore) AddComment(ctx context.Context, trackingSet string, id string, comment types.Comment) error {
	ret := _mock.Called(ctx, trackingSet, id, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, types.Comment) error); ok {
		r0 = returnFunc(ctx, trackingSet, id, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketStore_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockTicketStore_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
//   - comment types.Comment
func (_e *MockTicketStore_Expecter) AddComment(ctx interface{}, trackingSet interface{}, id interface{}, comment interface{}) *MockTicketStore_AddComment_Call {
	return &MockTicketStore_AddComment_Call{Call: _e.mock.On("AddComment", ctx, trackingSet, id, comment)}
}

func (_c *MockTicketStore_AddComment_Call) Run(run func(ctx context.Context, trackingSet string, id string, comment types.Comment)) *MockTicketStore_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 types.Comment
		if args[3] != nil {
			arg3 = args[3].(types.Comment)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTicketStore_AddComment_Call) Return(err error) *MockTicketStore_AddComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketStore_AddComment_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string, comment types.Comment) error) *MockTicketStore_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTicketStore
func (_mock *MockTicketStore) Create(ctx context.Context, trackingSet string, ticket types.Ticket) error {
	ret := _mock.Called(ctx, trackingSet, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Ticket) error); ok {
		r0 = returnFunc(ctx, trackingSet, ticket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticket types.Ticket
func (_e *MockTicketStore_Expecter) Create(ctx interface{}, trackingSet interface{}, ticket interface{}) *MockTicketStore_Create_Call {
	return &MockTicketStore_Create_Call{Call: _e.mock.On("Create", ctx, trackingSet, ticket)}
}

func (_c *MockTicketStore_Create_Call) Run(run func(ctx context.Context, trackingSet string, ticket types.Ticket)) *MockTicketStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Ticket
		if args[2] != nil {
			arg2 = args[2].(types.Ticket)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketStore_Create_Call) Return(err error) *MockTicketStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketStore_Create_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticket types.Ticket) error) *MockTicketStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTicketStore
func (_mock *MockTicketStore) Delete(ctx context.Context, trackingSet string, id string) error {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTicketStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockTicketStore_Expecter) Delete(ctx interface{}, trackingSet interface{}, id interface{}) *MockTicketStore_Delete_Call {
	return &MockTicketStore_Delete_Call{Call: _e.mock.On("Delete", ctx, trackingSet, id)}
}

func (_c *MockTicketStore_Delete_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockTicketStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketStore_Delete_Call) Return(err error) *MockTicketStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketStore_Delete_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) error) *MockTicketStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockTicketStore
func (_mock *MockTicketStore) Get(ctx context.Context, trackingSet string, id string) (types.Ticket, error) {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (types.Ticket, error)); ok {
		return returnFunc(ctx, trackingSet, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) types.Ticket); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Get(0).(types.Ticket)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockTicketStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockTicketStore_Expecter) Get(ctx interface{}, trackingSet interface{}, id interface{}) *MockTicketStore_Get_Call {
	return &MockTicketStore_Get_Call{Call: _e.mock.On("Get", ctx, trackingSet, id)}
}

func (_c *MockTicketStore_Get_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockTicketStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketStore_Get_Call) Return(ticket types.Ticket, err error) *MockTicketStore_Get_Call {
	_c.Call.Return(ticket, err)
	return _c
}

func (_c *MockTicketStore_Get_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) (types.Ticket, error)) *MockTicketStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTicketStore
func (_mock *MockTicketStore) List(ctx context.Context, trackingSet string, filter adapter.TicketFilter) ([]types.Ticket, error) {
	ret := _mock.Called(ctx, trackingSet, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []types.Ticket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, adapter.TicketFilter) ([]types.Ticket, error)); ok {
		return returnFunc(ctx, trackingSet, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, adapter.TicketFilter) []types.Ticket); ok {
		r0 = returnFunc(ctx, trackingSet, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Ticket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, adapter.TicketFilter) error); ok {
		r1 = returnFunc(ctx, trackingSet, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTicketStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTicketStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - filter adapter.TicketFilter
func (_e *MockTicketStore_Expecter) List(ctx interface{}, trackingSet interface{}, filter interface{}) *MockTicketStore_List_Call {
	return &MockTicketStore_List_Call{Call: _e.mock.On("List", ctx, trackingSet, filter)}
}

func (_c *MockTicketStore_List_Call) Run(run func(ctx context.Context, trackingSet string, filter adapter.TicketFilter)) *MockTicketStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 adapter.TicketFilter
		if args[2] != nil {
			arg2 = args[2].(adapter.TicketFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketStore_List_Call) Return(tickets []types.Ticket, err error) *MockTicketStore_List_Call {
	_c.Call.Return(tickets, err)
	return _c
}

func (_c *MockTicketStore_List_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, filter adapter.TicketFilter) ([]types.Ticket, error)) *MockTicketStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTicketStore
func (_mock *MockTicketStore) Update(ctx context.Context, trackingSet string, ticket types.Ticket) error {
	ret := _mock.Called(ctx, trackingSet, ticket)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Ticket) error); ok {
		r0 = returnFunc(ctx, trackingSet, ticket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTicketStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTicketStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticket types.Ticket
func (_e *MockTicketStore_Expecter) Update(ctx interface{}, trackingSet interface{}, ticket interface{}) *MockTicketStore_Update_Call {
	return &MockTicketStore_Update_Call{Call: _e.mock.On("Update", ctx, trackingSet, ticket)}
}

func (_c *MockTicketStore_Update_Call) Run(run func(ctx context.Context, trackingSet string, ticket types.Ticket)) *MockTicketStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Ticket
		if args[2] != nil {
			arg2 = args[2].(types.Ticket)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTicketStore_Update_Call) Return(err error) *MockTicketStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTicketStore_Update_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticket types.Ticket) error) *MockTicketStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
