// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-tracker/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetaPlanStore creates a new instance of MockMetaPlanStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetaPlanStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetaPlanStore {
	mock := &MockMetaPlanStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetaPlanStore is an autogenerated mock type for the MetaPlanStore type
type MockMetaPlanStore struct {
	mock.Mock
}

type MockMetaPlanStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetaPlanStore) EXPECT() *MockMetaPlanStore_Expecter {
	return &MockMetaPlanStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockMetaPlanStore
func (_mock *MockMetaPlanStore) Create(ctx context.Context, trackingSet string, mp types.MetaPlan) error {
	ret := _mock.Called(ctx, trackingSet, mp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.MetaPlan) error); ok {
		r0 = returnFunc(ctx, trackingSet, mp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetaPlanStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMetaPlanStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - mp types.MetaPlan
func (_e *MockMetaPlanStore_Expecter) Create(ctx interface{}, trackingSet interface{}, mp interface{}) *MockMetaPlanStore_Create_Call {
	return &MockMetaPlanStore_Create_Call{Call: _e.mock.On("Create", ctx, trackingSet, mp)}
}

func (_c *MockMetaPlanStore_Create_Call) Run(run func(ctx context.Context, trackingSet string, mp types.MetaPlan)) *MockMetaPlanStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.MetaPlan
		if args[2] != nil {
			arg2 = args[2].(types.MetaPlan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetaPlanStore_Create_Call) Return(err error) *MockMetaPlanStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetaPlanStore_Create_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, mp types.MetaPlan) error) *MockMetaPlanStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMetaPlanStore
func (_mock *MockMetaPlanStore) Delete(ctx context.Context, trackingSet string, id string) error {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetaPlanStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMetaPlanStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockMetaPlanStore_Expecter) Delete(ctx interface{}, trackingSet interface{}, id interface{}) *MockMetaPlanStore_Delete_Call {
	return &MockMetaPlanStore_Delete_Call{Call: _e.mock.On("Delete", ctx, trackingSet, id)}
}

func (_c *MockMetaPlanStore_Delete_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockMetaPlanStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetaPlanStore_Delete_Call) Return(err error) *MockMetaPlanStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetaPlanStore_Delete_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) error) *MockMetaPlanStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMetaPlanStore
func (_mock *MockMetaPlanStore) Get(ctx context.Context, trackingSet string, id string) (types.MetaPlan, error) {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (types.MetaPlan, error)); ok {
		return returnFunc(ctx, trackingSet, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) types.MetaPlan); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Get(0).(types.MetaPlan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetaPlanStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetaPlanStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockMetaPlanStore_Expecter) Get(ctx interface{}, trackingSet interface{}, id interface{}) *MockMetaPlanStore_Get_Call {
	return &MockMetaPlanStore_Get_Call{Call: _e.mock.On("Get", ctx, trackingSet, id)}
}

func (_c *MockMetaPlanStore_Get_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockMetaPlanStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetaPlanStore_Get_Call) Return(metaPlan types.MetaPlan, err error) *MockMetaPlanStore_Get_Call {
	_c.Call.Return(metaPlan, err)
	return _c
}

func (_c *MockMetaPlanStore_Get_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) (types.MetaPlan, error)) *MockMetaPlanStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMetaPlanStore
func (_mock *MockMetaPlanStore) List(ctx context.Context, trackingSet string) ([]types.MetaPlan, error) {
	ret := _mock.Called(ctx, trackingSet)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []types.MetaPlan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]types.MetaPlan, error)); ok {
		return returnFunc(ctx, trackingSet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []types.MetaPlan); ok {
		r0 = returnFunc(ctx, trackingSet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.MetaPlan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, trackingSet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetaPlanStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMetaPlanStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
func (_e *MockMetaPlanStore_Expecter) List(ctx interface{}, trackingSet interface{}) *MockMetaPlanStore_List_Call {
	return &MockMetaPlanStore_List_Call{Call: _e.mock.On("List", ctx, trackingSet)}
}

func (_c *MockMetaPlanStore_List_Call) Run(run func(ctx context.Context, trackingSet string)) *MockMetaPlanStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetaPlanStore_List_Call) Return(metaPlans []types.MetaPlan, err error) *MockMetaPlanStore_List_Call {
	_c.Call.Return(metaPlans, err)
	return _c
}

func (_c *MockMetaPlanStore_List_Call) RunAndReturn(run func(ctx context.Context, trackingSet string) ([]types.MetaPlan, error)) *MockMetaPlanStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockMetaPlanStore
func (_mock *MockMetaPlanStore) Update(ctx context.Context, trackingSet string, mp types.MetaPlan) error {
	ret := _mock.Called(ctx, trackingSet, mp)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.MetaPlan) error); ok {
		r0 = returnFunc(ctx, trackingSet, mp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetaPlanStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMetaPlanStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - mp types.MetaPlan
func (_e *MockMetaPlanStore_Expecter) Update(ctx interface{}, trackingSet interface{}, mp interface{}) *MockMetaPlanStore_Update_Call {
	return &MockMetaPlanStore_Update_Call{Call: _e.mock.On("Update", ctx, trackingSet, mp)}
}

func (_c *MockMetaPlanStore_Update_Call) Run(run func(ctx context.Context, trackingSet string, mp types.MetaPlan)) *MockMetaPlanStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.MetaPlan
		if args[2] != nil {
			arg2 = args[2].(types.MetaPlan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetaPlanStore_Update_Call) Return(err error) *MockMetaPlanStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetaPlanStore_Update_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, mp types.MetaPlan) error) *MockMetaPlanStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
