// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-tracker/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGraphStore creates a new instance of MockGraphStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGraphStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGraphStore {
	mock := &MockGraphStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGraphStore is an autogenerated mock type for the GraphStore type
type MockGraphStore struct {
	mock.Mock
}

type MockGraphStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGraphStore) EXPECT() *MockGraphStore_Expecter {
	return &MockGraphStore_Expecter{mock: &_m.Mock}
}

// AddEdge provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) AddEdge(ctx context.Context, trackingSet string, edge types.Edge) error {
	ret := _mock.Called(ctx, trackingSet, edge)

	if len(ret) == 0 {
		panic("no return value specified for AddEdge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Edge) error); ok {
		r0 = returnFunc(ctx, trackingSet, edge)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGraphStore_AddEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEdge'
type MockGraphStore_AddEdge_Call struct {
	*mock.Call
}

// AddEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - edge types.Edge
func (_e *MockGraphStore_Expecter) AddEdge(ctx interface{}, trackingSet interface{}, edge interface{}) *MockGraphStore_AddEdge_Call {
	return &MockGraphStore_AddEdge_Call{Call: _e.mock.On("AddEdge", ctx, trackingSet, edge)}
}

func (_c *MockGraphStore_AddEdge_Call) Run(run func(ctx context.Context, trackingSet string, edge types.Edge)) *MockGraphStore_AddEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Edge
		if args[2] != nil {
			arg2 = args[2].(types.Edge)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphStore_AddEdge_Call) Return(err error) *MockGraphStore_AddEdge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGraphStore_AddEdge_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, edge types.Edge) error) *MockGraphStore_AddEdge_Call {
	_c.Call.Return(run)
	return _c
}

// AddNode provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) AddNode(ctx context.Context, trackingSet string, ticketID string) error {
	ret := _mock.Called(ctx, trackingSet, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for AddNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGraphStore_AddNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNode'
type MockGraphStore_AddNode_Call struct {
	*mock.Call
}

// AddNode is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticketID string
func (_e *MockGraphStore_Expecter) AddNode(ctx interface{}, trackingSet interface{}, ticketID interface{}) *MockGraphStore_AddNode_Call {
	return &MockGraphStore_AddNode_Call{Call: _e.mock.On("AddNode", ctx, trackingSet, ticketID)}
}

func (_c *MockGraphStore_AddNode_Call) Run(run func(ctx context.Context, trackingSet string, ticketID string)) *MockGraphStore_AddNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphStore_AddNode_Call) Return(err error) *MockGraphStore_AddNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGraphStore_AddNode_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticketID string) error) *MockGraphStore_AddNode_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) Get(ctx context.Context, trackingSet string) (types.Graph, error) {
	ret := _mock.Called(ctx, trackingSet)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.Graph
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (types.Graph, error)); ok {
		return returnFunc(ctx, trackingSet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) types.Graph); ok {
		r0 = returnFunc(ctx, trackingSet)
	} else {
		r0 = ret.Get(0).(types.Graph)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, trackingSet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGraphStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
func (_e *MockGraphStore_Expecter) Get(ctx interface{}, trackingSet interface{}) *MockGraphStore_Get_Call {
	return &MockGraphStore_Get_Call{Call: _e.mock.On("Get", ctx, trackingSet)}
}

func (_c *MockGraphStore_Get_Call) Run(run func(ctx context.Context, trackingSet string)) *MockGraphStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGraphStore_Get_Call) Return(graph types.Graph, err error) *MockGraphStore_Get_Call {
	_c.Call.Return(graph, err)
	return _c
}

func (_c *MockGraphStore_Get_Call) RunAndReturn(run func(ctx context.Context, trackingSet string) (types.Graph, error)) *MockGraphStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlocking provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) GetBlocking(ctx context.Context, trackingSet string, ticketID string) ([]string, error) {
	ret := _mock.Called(ctx, trackingSet, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetBlocking")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, trackingSet, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphStore_GetBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlocking'
type MockGraphStore_GetBlocking_Call struct {
	*mock.Call
}

// GetBlocking is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticketID string
func (_e *MockGraphStore_Expecter) GetBlocking(ctx interface{}, trackingSet interface{}, ticketID interface{}) *MockGraphStore_GetBlocking_Call {
	return &MockGraphStore_GetBlocking_Call{Call: _e.mock.On("GetBlocking", ctx, trackingSet, ticketID)}
}

func (_c *MockGraphStore_GetBlocking_Call) Run(run func(ctx context.Context, trackingSet string, ticketID string)) *MockGraphStore_GetBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphStore_GetBlocking_Call) Return(strings []string, err error) *MockGraphStore_GetBlocking_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGraphStore_GetBlocking_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticketID string) ([]string, error)) *MockGraphStore_GetBlocking_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) GetChildren(ctx context.Context, trackingSet string, parentID string) ([]string, error) {
	ret := _mock.Called(ctx, trackingSet, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, trackingSet, parentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, trackingSet, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, parentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphStore_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type MockGraphStore_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - parentID string
func (_e *MockGraphStore_Expecter) GetChildren(ctx interface{}, trackingSet interface{}, parentID interface{}) *MockGraphStore_GetChildren_Call {
	return &MockGraphStore_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx, trackingSet, parentID)}
}

func (_c *MockGraphStore_GetChildren_Call) Run(run func(ctx context.Context, trackingSet string, parentID string)) *MockGraphStore_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphStore_GetChildren_Call) Return(strings []string, err error) *MockGraphStore_GetChildren_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockGraphStore_GetChildren_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, parentID string) ([]string, error)) *MockGraphStore_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetEdges provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) GetEdges(ctx context.Context, trackingSet string, ticketID string) ([]types.Edge, error) {
	ret := _mock.Called(ctx, trackingSet, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetEdges")
	}

	var r0 []types.Edge
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]types.Edge, error)); ok {
		return returnFunc(ctx, trackingSet, ticketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []types.Edge); ok {
		r0 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Edge)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGraphStore_GetEdges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEdges'
type MockGraphStore_GetEdges_Call struct {
	*mock.Call
}

// GetEdges is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticketID string
func (_e *MockGraphStore_Expecter) GetEdges(ctx interface{}, trackingSet interface{}, ticketID interface{}) *MockGraphStore_GetEdges_Call {
	return &MockGraphStore_GetEdges_Call{Call: _e.mock.On("GetEdges", ctx, trackingSet, ticketID)}
}

func (_c *MockGraphStore_GetEdges_Call) Run(run func(ctx context.Context, trackingSet string, ticketID string)) *MockGraphStore_GetEdges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphStore_GetEdges_Call) Return(edges []types.Edge, err error) *MockGraphStore_GetEdges_Call {
	_c.Call.Return(edges, err)
	return _c
}

func (_c *MockGraphStore_GetEdges_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticketID string) ([]types.Edge, error)) *MockGraphStore_GetEdges_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEdge provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) RemoveEdge(ctx context.Context, trackingSet string, edge types.Edge) error {
	ret := _mock.Called(ctx, trackingSet, edge)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEdge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Edge) error); ok {
		r0 = returnFunc(ctx, trackingSet, edge)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGraphStore_RemoveEdge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEdge'
type MockGraphStore_RemoveEdge_Call struct {
	*mock.Call
}

// RemoveEdge is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - edge types.Edge
func (_e *MockGraphStore_Expecter) RemoveEdge(ctx interface{}, trackingSet interface{}, edge interface{}) *MockGraphStore_RemoveEdge_Call {
	return &MockGraphStore_RemoveEdge_Call{Call: _e.mock.On("RemoveEdge", ctx, trackingSet, edge)}
}

func (_c *MockGraphStore_RemoveEdge_Call) Run(run func(ctx context.Context, trackingSet string, edge types.Edge)) *MockGraphStore_RemoveEdge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Edge
		if args[2] != nil {
			arg2 = args[2].(types.Edge)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphStore_RemoveEdge_Call) Return(err error) *MockGraphStore_RemoveEdge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGraphStore_RemoveEdge_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, edge types.Edge) error) *MockGraphStore_RemoveEdge_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveNode provides a mock function for the type MockGraphStore
func (_mock *MockGraphStore) RemoveNode(ctx context.Context, trackingSet string, ticketID string) error {
	ret := _mock.Called(ctx, trackingSet, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, trackingSet, ticketID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockGraphStore_RemoveNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNode'
type MockGraphStore_RemoveNode_Call struct {
	*mock.Call
}

// RemoveNode is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - ticketID string
func (_e *MockGraphStore_Expecter) RemoveNode(ctx interface{}, trackingSet interface{}, ticketID interface{}) *MockGraphStore_RemoveNode_Call {
	return &MockGraphStore_RemoveNode_Call{Call: _e.mock.On("RemoveNode", ctx, trackingSet, ticketID)}
}

func (_c *MockGraphStore_RemoveNode_Call) Run(run func(ctx context.Context, trackingSet string, ticketID string)) *MockGraphStore_RemoveNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGraphStore_RemoveNode_Call) Return(err error) *MockGraphStore_RemoveNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockGraphStore_RemoveNode_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, ticketID string) error) *MockGraphStore_RemoveNode_Call {
	_c.Call.Return(run)
	return _c
}
