// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockadapter

import (
	"context"

	"github.com/alexandremahdhaoui/forge-tracker/internal/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlanStore creates a new instance of MockPlanStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlanStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlanStore {
	mock := &MockPlanStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlanStore is an autogenerated mock type for the PlanStore type
type MockPlanStore struct {
	mock.Mock
}

type MockPlanStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlanStore) EXPECT() *MockPlanStore_Expecter {
	return &MockPlanStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPlanStore
func (_mock *MockPlanStore) Create(ctx context.Context, trackingSet string, plan types.Plan) error {
	ret := _mock.Called(ctx, trackingSet, plan)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Plan) error); ok {
		r0 = returnFunc(ctx, trackingSet, plan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlanStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPlanStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - plan types.Plan
func (_e *MockPlanStore_Expecter) Create(ctx interface{}, trackingSet interface{}, plan interface{}) *MockPlanStore_Create_Call {
	return &MockPlanStore_Create_Call{Call: _e.mock.On("Create", ctx, trackingSet, plan)}
}

func (_c *MockPlanStore_Create_Call) Run(run func(ctx context.Context, trackingSet string, plan types.Plan)) *MockPlanStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Plan
		if args[2] != nil {
			arg2 = args[2].(types.Plan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanStore_Create_Call) Return(err error) *MockPlanStore_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlanStore_Create_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, plan types.Plan) error) *MockPlanStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPlanStore
func (_mock *MockPlanStore) Delete(ctx context.Context, trackingSet string, id string) error {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlanStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPlanStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockPlanStore_Expecter) Delete(ctx interface{}, trackingSet interface{}, id interface{}) *MockPlanStore_Delete_Call {
	return &MockPlanStore_Delete_Call{Call: _e.mock.On("Delete", ctx, trackingSet, id)}
}

func (_c *MockPlanStore_Delete_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockPlanStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanStore_Delete_Call) Return(err error) *MockPlanStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlanStore_Delete_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) error) *MockPlanStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockPlanStore
func (_mock *MockPlanStore) Get(ctx context.Context, trackingSet string, id string) (types.Plan, error) {
	ret := _mock.Called(ctx, trackingSet, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 types.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (types.Plan, error)); ok {
		return returnFunc(ctx, trackingSet, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) types.Plan); ok {
		r0 = returnFunc(ctx, trackingSet, id)
	} else {
		r0 = ret.Get(0).(types.Plan)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, trackingSet, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPlanStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - id string
func (_e *MockPlanStore_Expecter) Get(ctx interface{}, trackingSet interface{}, id interface{}) *MockPlanStore_Get_Call {
	return &MockPlanStore_Get_Call{Call: _e.mock.On("Get", ctx, trackingSet, id)}
}

func (_c *MockPlanStore_Get_Call) Run(run func(ctx context.Context, trackingSet string, id string)) *MockPlanStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanStore_Get_Call) Return(plan types.Plan, err error) *MockPlanStore_Get_Call {
	_c.Call.Return(plan, err)
	return _c
}

func (_c *MockPlanStore_Get_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, id string) (types.Plan, error)) *MockPlanStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockPlanStore
func (_mock *MockPlanStore) List(ctx context.Context, trackingSet string) ([]types.Plan, error) {
	ret := _mock.Called(ctx, trackingSet)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []types.Plan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]types.Plan, error)); ok {
		return returnFunc(ctx, trackingSet)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []types.Plan); ok {
		r0 = returnFunc(ctx, trackingSet)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]types.Plan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, trackingSet)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlanStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockPlanStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
func (_e *MockPlanStore_Expecter) List(ctx interface{}, trackingSet interface{}) *MockPlanStore_List_Call {
	return &MockPlanStore_List_Call{Call: _e.mock.On("List", ctx, trackingSet)}
}

func (_c *MockPlanStore_List_Call) Run(run func(ctx context.Context, trackingSet string)) *MockPlanStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlanStore_List_Call) Return(plans []types.Plan, err error) *MockPlanStore_List_Call {
	_c.Call.Return(plans, err)
	return _c
}

func (_c *MockPlanStore_List_Call) RunAndReturn(run func(ctx context.Context, trackingSet string) ([]types.Plan, error)) *MockPlanStore_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPlanStore
func (_mock *MockPlanStore) Update(ctx context.Context, trackingSet string, plan types.Plan) error {
	ret := _mock.Called(ctx, trackingSet, plan)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, types.Plan) error); ok {
		r0 = returnFunc(ctx, trackingSet, plan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlanStore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPlanStore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - trackingSet string
//   - plan types.Plan
func (_e *MockPlanStore_Expecter) Update(ctx interface{}, trackingSet interface{}, plan interface{}) *MockPlanStore_Update_Call {
	return &MockPlanStore_Update_Call{Call: _e.mock.On("Update", ctx, trackingSet, plan)}
}

func (_c *MockPlanStore_Update_Call) Run(run func(ctx context.Context, trackingSet string, plan types.Plan)) *MockPlanStore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 types.Plan
		if args[2] != nil {
			arg2 = args[2].(types.Plan)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlanStore_Update_Call) Return(err error) *MockPlanStore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlanStore_Update_Call) RunAndReturn(run func(ctx context.Context, trackingSet string, plan types.Plan) error) *MockPlanStore_Update_Call {
	_c.Call.Return(run)
	return _c
}
